### ISSUE TITLE
Roadmap for v0.3

### ISSUE THREAD

**Issue by rutherfordcraze** [mass-driver/md-io#7]
Specific things I’m working on for 0.2 (not an exhaustive list):

- [x] Add Lambda (#5)
- [x] Add box-drawing characters (the extended unicode block, not the smaller ascii one)
- [x] Vertical metrics changes to support box-drawing alignment
- [x] Add block elements
- [x] Add Arrows
- [x] Improve `il1` distinction
- [x] Improve Windows rendering (probably just autohint)
- [x] Add bold master (I’ll probably add one bold style in 0.2, but defining the complete weight range will take time)
- [ ] ~Continue work on italics (won’t be in the 0.2 release)~
- [ ] ~Simplify the `ß` design a bit~
- [ ] ~Add more diacritics for European languages~

## Bold:
- [x] Uppercase
- [x] Lowercase
- [x] Numbers
- [x] Diacritics
- [x] Punctuation
- [x] Symbols
- [x] Interpolations

I’m going to aim for an early March release of 0.2, but depending on a lot of factors it could be earlier or later. Some of these issues might roll over to 0.3 if they’re looking like they’ll take too long.

**Comment by rutherfordcraze** [comment]
Update 0.2 will be live tomorrow (2021-03-15), but I’ll keep this issue open as a progress tracker for 0.3.

Issues which rolled over from 0.2:
- [x] Italics
- [x] Simplified `ß` design
- [x] Eastern European character support & diacritics
